<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon></ApplicationIcon>
    <AssemblyName>MaomaoDesktopPet</AssemblyName>
    <RootNamespace>MaomaoDesktopPet</RootNamespace>
    <Product>毛毛桌宠</Product>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Assets\Pet\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
